### PR TITLE
Compatiblity with Keycloak 23

### PR DESCRIPTION
**Pull request by cturkalj**
Fixes issue  #182

### CODE REVIEW

**Comment by jdreichmann** [comment]
Can confirm this works, when installed in keycloak 23.0.3, it exposes 84 more metrics.

However, the "featured" metrics `keycloak_logins`, `keycloak_login_attempts` etc do not seem to be present

**Review by jdreichmann — APPROVED** [review]

**Comment by mmadoo** [comment]
When does this PR will be merged ?

**Comment by pb82** [comment]
will do a proper release later today

**Comment by pb82** [comment]
The release is done now. Do we need to include a note that this only supports Keycloak 23 and above?

**Pull request merged**
