### PR TITLE
Fix the dependency to work with Keycloak 16.0.0 

### PR DESCRIPTION
**Pull request by jonathanvila**
## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 
#124 

## What
Explicitly specify the RestEasy version that comes with Wildfly 25 instead of the one specified in Keycloak
Changed the method to register the Filter

## Why
RestEasy v4 has changed the API

## How
Explicit specification of the resteasy dependency on the build.gradle
Modified the way to register the filter

## Verification Steps
Already present tests are still working
Deployed Keycloak 16.0.0 with this new code and KC starts and the metrics endpoint responds with the metrics

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users.

### CODE REVIEW

**Comment by pb82** [comment]
@jonathanvila is this already covered by #120 ?

**Comment by pb82** [comment]
@jonathanvila can you please check if release 2.5.3 works on Keycloak 16?

**Comment by ehsan-tashkhisi** [comment]
I am still experiencing this problem in Keycloak 16.1.0. With `keycloak-metrics-spi.2.5.3`, I think _compatibility with Keycloak 15+_ for this release would be misleading.

**Comment by jonathanvila** [comment]
@pb82 I have tested that with KC 16.1.0 and it works fine
Thank you.

**Pull request closed without merging**
