### PR TITLE
WIP - AEROGEAR-2096 Made tests working

### PR DESCRIPTION
**Pull request by aliok**
WIP!

Commits:
* 6c46795 : made tests working. disabled tests for IMPERSONATE events which are gonna be removed later
* ce81e09 : added `.editorconfig` for consistent formatting. took it from https://github.com/aerogear/aerogear-android-sdk/blob/40e8dc33674b2bcf620c3b00ba12d7fc9ce78ea8/.editorconfig
* 4e30387 : got rid of impersonate business logic as discussed with @pb82 and @josemigallas 
* 39cddae : Got rid of some static stuff. Singleton instance is static anyway
* d630897 : Added tests for different login cases and register cases
* 688330e : Add tests for login error - created Tuple class to use in tests

### CODE REVIEW

**Comment by aliok** [comment]
hey @pb82 this PR is still in progress :)

**Comment by josemigallas** [comment]
Shoot first, ask later @pb82 😄

**Comment by aliok** [comment]
Closing this. Gonna create a new one for testing Jenkins testing

**Comment by aliok** [comment]
Created https://github.com/aerogear/keycloak-metrics-spi/pull/10

**Pull request closed without merging**
