### PR TITLE
Pipeline for releasing Docker init container

### PR DESCRIPTION
**Pull request by kilmajster**
Hi, I've created Github action based pipeline that allows to promote release by Github release [form](https://github.com/aerogear/keycloak-metrics-spi/releases/new). It adds built jar file into Github release and also creates and publishes init container into Docker hub. To make this 100% working you'd need to have account on Docker hub and create repo for this project, then create token that will allow the pipeline to publish image into Docker hub. Token from Docker hub should be added to this Github repo as repository secret called `DOCKER_HUB_TOKEN`. Working test release can be found in my fork [here](https://github.com/kilmajster/keycloak-metrics-spi/runs/4000264666?check_suite_focus=true)
If you need more details about configuration, just let me know :)

Regards, Łukasz Włódarczyk

## Motivation
#34

## What
Pipeline that publishes jar into Github releases and init container into Docker hub

## Why
To allow using this provider with Helm charts

## How
Release process with this pipeline looks like following:
1. You create new tag using standard Github release mechanism, e.g. tag = `2.5.3`
2. Pipeline is executing tests
3. Pipeline sets project version based on git tag and build jar
5. Jar file is added into Github release
6. Jar file is added into Docker image
7. Docker image is tagged same as Github tag and also as `latest`
8. Docker images are pushed into Docker hub

## Verification Steps
You can verify that jar is added into Github release in my fork [here](https://github.com/kilmajster/keycloak-metrics-spi/releases/tag/2.5.3)  
To verify if docker container contains jar file you can do following:
```bash
docker run --rm -it --entrypoint sh kilmajster/keycloak-metrics-spi

# then into docker container
 cd keycloak-metrics-spi
 ls -al
 
 # and also for eg. to verify if version is set correctly
 
 unzip keycloak-metrics-spi-2.5.3.jar
 
 ...
 
 cat META-INF/MANIFEST.MF
```

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress

- [x] Finished task
## Additional Notes

### CODE REVIEW

**Comment by pb82** [comment]
thanks @kilmajster , this is really nice! I'll have a look through it this week and hopefully we can merge it.

**Comment by kilmajster** [comment]
Do Jankinsfile  will be still needed with this pipeline or I can remove it as well?

**Comment by sbaerlocher** [comment]
@kilmajster @pb82 Is there already more infos what this PR can be merged?

**Comment by kilmajster** [comment]
Hi @sbaerlocher, this PR seems to be little bit forgotten ;) I merged it with upstream and promoted test release to confirm that is still working (pipeline: https://github.com/kilmajster/keycloak-metrics-spi/runs/5828438512?check_suite_focus=true and docker: https://hub.docker.com/repository/docker/kilmajster/keycloak-metrics-spi). I am not a member of the project so I can't merge it. 

@pb82 I saw that pom.xml was added, if you are switching to this project to maven I can change this pipeline to maven one. Also in my similar [personal project](https://github.com/kilmajster/keycloak-username-password-attribute-authenticator) I got [pipeline](https://github.com/kilmajster/keycloak-username-password-attribute-authenticator/runs/5234413298?check_suite_focus=true) that is able to release artifact to maven central, so if you are interested in such mechanism I will be happy to help with this :)

**Comment by james-callahan** [comment]
I'd love to see this (or something like it) merged.

It looks like it needs a rebase at the moment?

**Comment by kilmajster** [comment]
is up to date no :)

**Comment by james-callahan** [comment]
> is up to date now :)

Looks like it may need to be rebased again since the 4.0.0 release

@diversit would you be able to review/merge this?
It'd be a huge help for us manage a deployment of keycloak-metrics-spi

**Comment by diversit** [comment]
I am happy to review but I’m on holiday now so that would be end of august
earliest.

**Comment by diversit** [comment]
Yes, I’ll review it tomorrow and get back to you

**Comment by kilmajster** [comment]
I've synced my changes with an upstream and also bumped java version to 17 in the release job - here is a pipeline I ran to promote test release with my personal docker hub creds https://github.com/kilmajster/keycloak-metrics-spi/actions/runs/6016566819/job/16320824108

**Comment by james-callahan** [comment]
@diversit ping?

**Comment by lerminou** [comment]
hi, any news for this topic ?

**Comment by diversit** [comment]
Changes look fine, but the PR requires an update due to conflicts.

@james-callahan Sorry for the late reply. I'm flattered of being asked to review and merge this PR, but I am not the owner of this repository nor a contributor with review capabilities. So I cannot help you. Perhaps @pb82 ?

**Comment by kilmajster** [comment]
With quarkus keycloak init containers are no more required to use custom providers. So this PR is no more relevant.

**Pull request closed without merging**
