### PR TITLE
Merge mobile-metrics branch to master

### PR DESCRIPTION
**Pull request by aliok**
@josemigallas @pb82 
Any reason not to?

### CODE REVIEW

**Comment by pb82** [comment]
👀

**Comment by pb82** [comment]
@aliok Let's merge it back. @josemigallas any concerns from your side? I think the collected Metrics are what you generally would expect, nothing really mobile specific.

**Comment by josemigallas** [comment]
Having a quick look now

**Comment by josemigallas** [comment]
I don't have any strong opinions here to be honest. I think we could freely merge it since Aerogear means Mobile but @pb82 has a point too.

**Comment by pb82** [comment]
@josemigallas @aliok I think it's better to merge it back. There's not advantage in maintaining this extra branch and all the changes in the branch can be in master just as well.

**Comment by aliok** [comment]
@david-martin I still can't merge stuff on this project :(

@josemigallas can you merge it for me?

**Pull request merged**
